version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "e-commerce-api-v1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jo89pfkdlwkt"
s3_prefix = "e-commerce-api-v1"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
